import type { RegionType, StateRef } from '@/types/domain';

// Must stay in sync with supabase/seed.sql's `states` inserts.
export const STATE_REFS: StateRef[] = [
  { code: 'AL', name: 'Alabama', regionType: 'us_state', fipsOrGeoId: '01' },
  { code: 'AK', name: 'Alaska', regionType: 'us_state', fipsOrGeoId: '02' },
  { code: 'AZ', name: 'Arizona', regionType: 'us_state', fipsOrGeoId: '04' },
  { code: 'AR', name: 'Arkansas', regionType: 'us_state', fipsOrGeoId: '05' },
  { code: 'CA', name: 'California', regionType: 'us_state', fipsOrGeoId: '06' },
  { code: 'CO', name: 'Colorado', regionType: 'us_state', fipsOrGeoId: '08' },
  { code: 'CT', name: 'Connecticut', regionType: 'us_state', fipsOrGeoId: '09' },
  { code: 'DE', name: 'Delaware', regionType: 'us_state', fipsOrGeoId: '10' },
  { code: 'DC', name: 'District of Columbia', regionType: 'us_state', fipsOrGeoId: '11' },
  { code: 'FL', name: 'Florida', regionType: 'us_state', fipsOrGeoId: '12' },
  { code: 'GA', name: 'Georgia', regionType: 'us_state', fipsOrGeoId: '13' },
  { code: 'HI', name: 'Hawaii', regionType: 'us_state', fipsOrGeoId: '15' },
  { code: 'ID', name: 'Idaho', regionType: 'us_state', fipsOrGeoId: '16' },
  { code: 'IL', name: 'Illinois', regionType: 'us_state', fipsOrGeoId: '17' },
  { code: 'IN', name: 'Indiana', regionType: 'us_state', fipsOrGeoId: '18' },
  { code: 'IA', name: 'Iowa', regionType: 'us_state', fipsOrGeoId: '19' },
  { code: 'KS', name: 'Kansas', regionType: 'us_state', fipsOrGeoId: '20' },
  { code: 'KY', name: 'Kentucky', regionType: 'us_state', fipsOrGeoId: '21' },
  { code: 'LA', name: 'Louisiana', regionType: 'us_state', fipsOrGeoId: '22' },
  { code: 'ME', name: 'Maine', regionType: 'us_state', fipsOrGeoId: '23' },
  { code: 'MD', name: 'Maryland', regionType: 'us_state', fipsOrGeoId: '24' },
  { code: 'MA', name: 'Massachusetts', regionType: 'us_state', fipsOrGeoId: '25' },
  { code: 'MI', name: 'Michigan', regionType: 'us_state', fipsOrGeoId: '26' },
  { code: 'MN', name: 'Minnesota', regionType: 'us_state', fipsOrGeoId: '27' },
  { code: 'MS', name: 'Mississippi', regionType: 'us_state', fipsOrGeoId: '28' },
  { code: 'MO', name: 'Missouri', regionType: 'us_state', fipsOrGeoId: '29' },
  { code: 'MT', name: 'Montana', regionType: 'us_state', fipsOrGeoId: '30' },
  { code: 'NE', name: 'Nebraska', regionType: 'us_state', fipsOrGeoId: '31' },
  { code: 'NV', name: 'Nevada', regionType: 'us_state', fipsOrGeoId: '32' },
  { code: 'NH', name: 'New Hampshire', regionType: 'us_state', fipsOrGeoId: '33' },
  { code: 'NJ', name: 'New Jersey', regionType: 'us_state', fipsOrGeoId: '34' },
  { code: 'NM', name: 'New Mexico', regionType: 'us_state', fipsOrGeoId: '35' },
  { code: 'NY', name: 'New York', regionType: 'us_state', fipsOrGeoId: '36' },
  { code: 'NC', name: 'North Carolina', regionType: 'us_state', fipsOrGeoId: '37' },
  { code: 'ND', name: 'North Dakota', regionType: 'us_state', fipsOrGeoId: '38' },
  { code: 'OH', name: 'Ohio', regionType: 'us_state', fipsOrGeoId: '39' },
  { code: 'OK', name: 'Oklahoma', regionType: 'us_state', fipsOrGeoId: '40' },
  { code: 'OR', name: 'Oregon', regionType: 'us_state', fipsOrGeoId: '41' },
  { code: 'PA', name: 'Pennsylvania', regionType: 'us_state', fipsOrGeoId: '42' },
  { code: 'RI', name: 'Rhode Island', regionType: 'us_state', fipsOrGeoId: '44' },
  { code: 'SC', name: 'South Carolina', regionType: 'us_state', fipsOrGeoId: '45' },
  { code: 'SD', name: 'South Dakota', regionType: 'us_state', fipsOrGeoId: '46' },
  { code: 'TN', name: 'Tennessee', regionType: 'us_state', fipsOrGeoId: '47' },
  { code: 'TX', name: 'Texas', regionType: 'us_state', fipsOrGeoId: '48' },
  { code: 'UT', name: 'Utah', regionType: 'us_state', fipsOrGeoId: '49' },
  { code: 'VT', name: 'Vermont', regionType: 'us_state', fipsOrGeoId: '50' },
  { code: 'VA', name: 'Virginia', regionType: 'us_state', fipsOrGeoId: '51' },
  { code: 'WA', name: 'Washington', regionType: 'us_state', fipsOrGeoId: '53' },
  { code: 'WV', name: 'West Virginia', regionType: 'us_state', fipsOrGeoId: '54' },
  { code: 'WI', name: 'Wisconsin', regionType: 'us_state', fipsOrGeoId: '55' },
  { code: 'WY', name: 'Wyoming', regionType: 'us_state', fipsOrGeoId: '56' },
  { code: 'AB', name: 'Alberta', regionType: 'ca_province', fipsOrGeoId: 'CA-AB' },
  { code: 'BC', name: 'British Columbia', regionType: 'ca_province', fipsOrGeoId: 'CA-BC' },
  { code: 'MB', name: 'Manitoba', regionType: 'ca_province', fipsOrGeoId: 'CA-MB' },
  { code: 'NB', name: 'New Brunswick', regionType: 'ca_province', fipsOrGeoId: 'CA-NB' },
  { code: 'NL', name: 'Newfoundland and Labrador', regionType: 'ca_province', fipsOrGeoId: 'CA-NL' },
  { code: 'NS', name: 'Nova Scotia', regionType: 'ca_province', fipsOrGeoId: 'CA-NS' },
  { code: 'NT', name: 'Northwest Territories', regionType: 'ca_province', fipsOrGeoId: 'CA-NT' },
  { code: 'NU', name: 'Nunavut', regionType: 'ca_province', fipsOrGeoId: 'CA-NU' },
  { code: 'ON', name: 'Ontario', regionType: 'ca_province', fipsOrGeoId: 'CA-ON' },
  { code: 'PE', name: 'Prince Edward Island', regionType: 'ca_province', fipsOrGeoId: 'CA-PE' },
  { code: 'QC', name: 'Quebec', regionType: 'ca_province', fipsOrGeoId: 'CA-QC' },
  { code: 'SK', name: 'Saskatchewan', regionType: 'ca_province', fipsOrGeoId: 'CA-SK' },
  { code: 'YT', name: 'Yukon Territory', regionType: 'ca_province', fipsOrGeoId: 'CA-YT' },
];

export const KNOWN_STATE_CODES: ReadonlySet<string> = new Set(STATE_REFS.map((s) => s.code));

export function regionTypeForCode(code: string): RegionType | null {
  return STATE_REFS.find((s) => s.code === code)?.regionType ?? null;
}
